package com.alexjlockwood.twentyfortyeight.ui
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFb22d00)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdacf)
val md_theme_light_onPrimaryContainer = Color(0xFF3b0800)
val md_theme_light_secondary = Color(0xFF00687c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFaaedff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f27)
val md_theme_light_tertiary = Color(0xFF6b5d2f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf5e1a6)
val md_theme_light_onTertiaryContainer = Color(0xFF231b00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a18)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a18)
val md_theme_light_surfaceVariant = Color(0xFFf5ded8)
val md_theme_light_onSurfaceVariant = Color(0xFF53433f)
val md_theme_light_outline = Color(0xFF86736e)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeeb)
val md_theme_light_inverseSurface = Color(0xFF362f2d)

val md_theme_dark_primary = Color(0xFFffb49d)
val md_theme_dark_onPrimary = Color(0xFF601400)
val md_theme_dark_primaryContainer = Color(0xFF882000)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdacf)
val md_theme_dark_secondary = Color(0xFF55d6f4)
val md_theme_dark_onSecondary = Color(0xFF003641)
val md_theme_dark_secondaryContainer = Color(0xFF004e5d)
val md_theme_dark_onSecondaryContainer = Color(0xFFaaedff)
val md_theme_dark_tertiary = Color(0xFFd8c58d)
val md_theme_dark_onTertiary = Color(0xFF3a2f05)
val md_theme_dark_tertiaryContainer = Color(0xFF53461a)
val md_theme_dark_onTertiaryContainer = Color(0xFFf5e1a6)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a18)
val md_theme_dark_onBackground = Color(0xFFede0dd)
val md_theme_dark_surface = Color(0xFF201a18)
val md_theme_dark_onSurface = Color(0xFFede0dd)
val md_theme_dark_surfaceVariant = Color(0xFF53433f)
val md_theme_dark_onSurfaceVariant = Color(0xFFd8c2bc)
val md_theme_dark_outline = Color(0xFFa08c87)
val md_theme_dark_inverseOnSurface = Color(0xFF201a18)
val md_theme_dark_inverseSurface = Color(0xFFede0dd)

val seed = Color(0xFFe94913)
val error = Color(0xFFba1b1b)